CONTRIBUTING.md

This file was still referencing `pilot` instead of `gym`.

Fix: Reference `gym` instead of `pilot`

---

lib/gym/build_command_generator.rb
lib/gym/options.rb
spec/build_command_generator_spec.rb

xcodebuild does not take an -xcargs option since it just takes the key-value pairs directly.
Also multiple key-value pairs need to be provided separately in the command, instead of having quotes around all of them (e.g. `A=1 B=2` instead of `'A=1 B=2'`) so I removed the quoting. This matches the behavior of shenzhen, and my Fastfile that worked with ipa/shenzhen now works with gym with little modification. Since no one could have been relying on xcargs with gym before this commit, I don't think this change should disrupt anyone.
Fixes #15, updated test passes

Remove `-xcargs` option and fix extra escaping around xcargs

---

lib/gym/package_command_generator.rb

This fixed #31 for me. The dSYM file was copied along with the ipa, both when an 'output_directory' was specified and when it was not.

Change dSYM extension to be case-sensitive.

---

lib/gym/options.rb
lib/gym/runner.rb

* removes check for the config_item if the folder exists
* adds mkdir_p command for the output_directory in move_results:runner.rb

Creates output_directory if it doesn't exist

---

lib/gym/detect_values.rb
lib/gym/project.rb

I ran into an issue where fastlane was selecting an error message as the scheme, and then trying to build  with the scheme set to the error message!
```
[09:16:40]: --- Step: gym ---
[09:16:40]: -----------------
[09:16:40]: xcrun xcodebuild -list -workspace './XXXXXXXXXXXXX.xcworkspace'
[09:16:41]: Couldn't find specified scheme 'XXXXXXXXXXXXX'.
[09:16:41]: xcrun xcodebuild -showBuildSettings -workspace './XXXXXXXXX.xcworkspace' -scheme 'There are no schemes in workspace "XXXXXXXXXXXXX".'
```
That last xcrun command would hang indefinitely.
The fix checks for the error message in project.rb and returns an empty array if the error message is seen. Also, detect_values.rb adds an error message with the probable fix -- share the scheme in your workspace.
Thanks for the awesome tool!

Fix hang when no schemes are found

---

lib/gym/package_command_generator.rb
spec/package_command_generator_spec.rb

A single quote in the product name was the reason for a crash during packaging:
```sh
/usr/bin/xcrun /tmp/PackageApplication4Gym -v '...path to product's name.app'
```
I had to quickly fix this, since I cannot change the product name.
It is working for me now.

Fix crash with apostrophes in product name

---

lib/assets/GymfileTemplate

xcodebuild does not think 9.0 is a valid value, but it does like iphoneos9.0

Change sdk in GymfileTemplate

---

lib/gym/generators/build_command_generator.rb
spec/build_command_generator_spec.rb

Create xcodebuild.log file containing detailed xcodebuild output.
This is very useful for debugging.
The implementation is simple, it creates xcodebuild-SchemeName.log file.

Generate xcodebuild.log for more details

---

lib/gym/generators/build_command_generator.rb
lib/gym/options.rb
spec/build_command_generator_spec.rb

Added option ```buildlog_path``` to change the location of the xcodebuild log. By default it is ```~/Library/Logs/gym```.
If ```buildlog_path``` is set to ```/my/location```, then the final build log will end up to ```/my/location``` folder instead of ```~/Library/Logs/gym```.
This is useful in specific cases when it is desired to have to build log file in a different location.

Added buildlog_path option to change the location of the xcodebuild logs

---

lib/gym/generators/build_command_generator.rb
lib/gym/runner.rb

This pull request solves the problem with the generated archive being reported as invalid by gym even when it wasn't. 
The problem was that the `BuildCommandsGenerator.archive_path` was assumed to always have the extension ".xcarchive". This pull request adds the extension onto the `archive_path` if it wasn't the extension already

Fix for issue #115, 'Generated archive is invalid'

---

README.md

Document that `--export_method` should be passed if you want an AdHoc (or any non-AppStore/TF) build.
Took me like two hours to figure out how to make the new Xcode export API work, battling Gym, and trying to decipher error logs, just to realize (after peeking into the export configuration plist) that Gym defaults the export method to "app-store".
AdHoc builds are still pretty common, so it's worth documenting it right on the front page IMHO.

Mention --export_method in the Readme

---

lib/gym/runner.rb

When building an application with many frameworks, each framework
will produce it's own dSYM file. These need to be included in the
dSYM zip file to allow for symbolication of crashes in these
frameworks.
Really we just need the archive path, but this will allow for
easy backward compatibility with existing code.

Zip all dSYM files together

---

lib/gym/generators/build_command_generator.rb
lib/gym/options.rb

We are using gym in our ci set up teamcity, and with the output from xcodebuild even with xcpretty on chrome doesn't load or takes forever to load the build log. A lot of the times the build completes but code signing fails or something like that. So it would be nice to suppress all xcode compile output and only keep the fastlane stuff.
We can still get to the log on the build agent if needed.
Not sure if this is the best approach, but a quick solution. If you can think of a better way that would be awesome.

Add option to suppress xcodebuild output

---

lib/gym.rb
lib/gym/runner.rb
lib/gym/xcodebuild_fixes/watchkit2_fix.rb
lib/gym/xcodebuild_fixes/watchkit_fix.rb

Nearly the same like the WatchOS 1 fix. I also adapted the WatchOS 1 hack, because it's also failing if you have both Support folders in the binary. Currently it's only working for the one or the other, not both. I don't know if that's a real use case. I also checked a WatchOS 1 plist and didn't find any other way to detect WatchOS 1.
Uploaded WatchOS2 to iTC without any issues ☕️

Added Fix for WatchKit 2.0 Support. (Apple Should fix their build chain)

---

lib/gym/generators/build_command_generator.rb

Basically, the same fix as [here](https://github.com/fastlane/scan/pull/63).
It disables xcpretty colored output when `FASTLANE_DISABLE_COLORS ` env variable is set.

Disable colors in xcpretty when FASTLANE_DISABLE_COLORS is set

---

lib/gym/detect_values.rb

When used with ````fastlane````, try to see if a ````Gymfile```` file is available in the current directory (````fastlane/````) and load the configuration parameters from there.

Try loading the Gymfile from the current directory

---

lib/gym/generators/package_command_generator_xcode7.rb
spec/package_command_generator_xcode7_spec.rb

Changed the XCode 7 package command generator to use standard Ruby tempfile class to obtain tempfile instead of using /tmp/current_epoch_seconds. 
I was running into tempfile name collision issues while running the build for three different targets concurrently.
A bigger question would be how come gym reaches the packaging stage for three different processes at the exact same second, but I haven't managed to figure that out. My guess is that it's something to do with XCode locking down on something and releasing it.

small change to tempfile name generation

---

lib/gym/xcodebuild_fixes/watchkit2_fix.rb

_WatchKit Fix_ module was not matched as Watch OS 2 application for ipa file that build with Version 7.2 (7C68).

Update `Gym::XcodebuildFixes::watchkit2?` to match watchos2.1

---

lib/gym/runner.rb

Hey @KrauseFx,
I was trying to build my tvos project with `gym`, but for some reason, no ipa was being generated.
After some debugging, I found this file. Adding the line made the ipa and dsym generates for me. I haven't tested any other scenario with this fix.
The tests pass (26 examples, 0 failures). I tried writing a test for this, but I couldn't quickly think of something that doesn't involve xcodebuild.
Please let me know if you'd like me to check more cases or update something else.

Fixed issue with creating ipa and dsym for tvos

---

README.md
lib/assets/wrap_xcodebuild/xcbuild-safe.sh
lib/gym/generators/package_command_generator_xcode7.rb
lib/gym/xcodebuild_fixes/package_application_fix.rb
spec/package_command_generator_xcode7_spec.rb

This pull request aims to provide a safe wrapper.
The xcbuild-wrapper.sh originates from a gist linked from a stackoverflow, and was modified to make sure it works when:
1. using rvm
2. using rbenv
3. using system ruby under the following conditions:
```
export GEM_HOME=/Users/lacostej/.gem/ruby/2.0.0
export PATH=/Users/lacostej/.gem/ruby/2.0.0/bin:$PATH
gem install bundler
bundle install
fastlane ...
```
I suspect this is good enough and I don't need to use sudo to test the same thing.

Issue #168 wrap xcodebuild calls within ruby system environment

---

lib/gym/generators/build_command_generator.rb

Addressing issue #107 
Tested with single quote and brackets in product name

Shell escape product name in build command

---

lib/gym/runner.rb

For Mac apps I had an issue, `.app` disappeared from xcode archive, generated by gym. It wasn't the case, when destination `.app` existed in project directory, but it didn't get overwrited with new archive.  
So, I've replace `mv` with `cp_r` command, because in case of Mac app original .app archive should be preserved in source archive directory.

Replaced move of .app archive with copy for Mac projects

---

lib/gym/options.rb
spec/options_spec.rb

In this PR  I added [new mechanism](https://github.com/fastlane/deliver/pull/545) for handling conflicts between `workspace` and `project` options + updated specs.
Feedback and comments are greatly appreciated :smiley_cat:

Use conflicting options mechanism for workspace and project paths

---

README.md
examples/standard/ExampleExport.plist
lib/gym/detect_values.rb
lib/gym/generators/package_command_generator.rb
lib/gym/generators/package_command_generator_legacy.rb
lib/gym/generators/package_command_generator_xcode7.rb
lib/gym/options.rb
lib/gym/runner.rb
spec/package_command_generator_xcode7_spec.rb

Hi,
As promised. I've added support for `-exportOptionsPlist` (as `:export_options`) and app thinning. With this pull request user will be able to provide path to export plist file or hash of options. In both cases some export options can be overridden by `:include_symbols`, `:include_bitcode`, `:export_method` and `:export_team_id`. To the output directory are copied `manifest.plist`, `app-thinning.plist`, `App Thinning Size Report.txt` files and the `Apps` folder with thinned ipa files.

Added support for `export_options` and app thinning

---

lib/gym/generators/build_command_generator.rb
lib/gym/options.rb
spec/build_command_generator_spec.rb

Hi,
The `:archive_path` options it the full path to the xcarchive bundle. Sometimes it is useful to provide path to the directory where xcarchive will be stored (without archive name). That is why I've added `:build_path`, which is a path to folder where archive will be created.

Added `build_path` option

---

lib/gym/generators/build_command_generator.rb

Hi,
I noticed that the `build_path` folder was not created by `gym` when `:build_path` parameter was passed. Right now current behaviour doesn't break anything because `export` action on `xcodebuild` automatically creates the folder. But if in the future someone wants to use this parameter, it would be nice to have this already done.
PS. Sorry that I didn't check this behaviour before :cry:

Fixed `mkdir -p` for `build_path`.

---

README.md

Boolean command line flags do not take parameters, so removing it from this example will prevent users from learning a style that doesn't really work

Fix example use of --use_legacy_build_api flag

---

lib/gym/error_handler.rb
lib/gym/options.rb
lib/gym/runner.rb

Added an option to only export an ipa file from a xarchive.
For me it is required to export development, adhoc and appstore version of an build. This option enables me to skip two build processes and only export ipas from the same build archive.

adding option to just export ipa from archive_path

---

spec/build_command_generator_spec.rb
spec/gymfile_spec.rb
spec/package_command_generator_legacy_spec.rb
spec/package_command_generator_xcode7_spec.rb

Makes the gym tests much faster (26s -> 7s on my machine). It does this by limiting the number of times `FastlaneCore::Project` objects are instantiated and thus need to shell out to Xcode tools. A future improvement could be to separate the concern of testing `Project` class interactions with Xcode tools from downstream consumers like gym.
This caching is performed at the spec file level, so it depends on each spec file running against roughly the same project configuration for all of its tests. All of ours basically do! Also, the more test examples exist per file, the larger the savings.
This caching increases the complexity of a somewhat complicated code area by breaking some of the `Configuration` object sharing that happens internally so that side-effecting changes between `Project` …

Improve the speed of the Gym tests
